Added cache-warm bin and live/readiness tests in containers, fixed issue with parsing variables that require parsing

diff --git a/templates/docker-config b/templates/docker-config
--- a/templates/docker-config
+++ b/templates/docker-config
@@ -4,9 +4,22 @@
 #
 set -e
 
+touch $CONFIG_PATHS_CONTAINER_STATUS
+if [ ! -f "$CONFIG_PATHS_CONTAINER_STATUS" ];
+then
+    echo "Error: Can't create container_status file $CONFIG_PATHS_CONTAINER_STATUS";
+    exit 1;
+fi
+
+echo "### Starting container configuration"
+echo "running_config" > $CONFIG_PATHS_CONTAINER_STATUS
+
 for config_script in ${BUILDER_TARGETS_FOLDERS_CONTAINER_CONFIG}/*; 
 do
     $config_script 1>/dev/stdout 2>/dev/stderr; 
 done;
+
+echo "### Finished container configuration"
+echo "ready" > $CONFIG_PATHS_CONTAINER_STATUS
 
 exit 0
diff --git a/templates/docker-run b/templates/docker-run
--- a/templates/docker-run
+++ b/templates/docker-run
@@ -2,12 +2,13 @@
 #
 # Run command
 #
-set -xe
+set -e
 
-echo "### Start container configuration\n"
+# Configuration
 $(which docker-config)
-echo "### Finished container configuration\n"
 
-echo "### Start container command"
-${BUILD_CMD}
+echo "### Starting container service"
+sh -c "${BUILD_CMD}"
+
+# Container command is failed if exiting here
 exit $?
